'use client';
import {useEffect,useState,FormEvent} from 'react';
import {authClient} from '../lib/client';
export default function AuthGate({children}:{children:React.ReactNode}){
 const [ready,setReady]=useState(false),[cloud,setCloud]=useState(false),[signed,setSigned]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[signup,setSignup]=useState(false),[recovery,setRecovery]=useState(false);
 useEffect(()=>{if(new URLSearchParams(window.location.hash.slice(1)).get('type')==='recovery')setRecovery(true);let live=true;let unsub:(()=>void)|undefined;authClient().then(async c=>{if(!live)return;if(!c){setReady(true);return;}setCloud(true);const {data}=await c.auth.getSession();if(!live)return;setSigned(!!data.session);setReady(true);const {data:sub}=c.auth.onAuthStateChange((event,session)=>{setSigned(!!session);if(event==='PASSWORD_RECOVERY')setRecovery(true);});unsub=()=>sub.subscription.unsubscribe();}).catch(e=>setError(e.message));return()=>{live=false;unsub?.();};},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const c=await authClient();if(!c)return;const result=recovery?await c.auth.updateUser({password}):signup?await c.auth.signUp({email,password}):await c.auth.signInWithPassword({email,password});if(result.error)throw new Error(recovery?'Não foi possível trocar a senha. Solicite outro link.':signup?'Não foi possível criar a conta. Confira os dados e tente novamente.':'Não foi possível entrar. Confira e-mail, senha e confirmação da conta.');setPassword('');if(recovery)setRecovery(false);if(signup)setNotice('Confira seu e-mail para confirmar o cadastro. Se não receber, peça ao responsável para criar sua conta no Supabase.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reset(){setBusy(true);setError('');try{const c=await authClient();const result=await c?.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(result?.error)throw new Error('Não foi possível enviar o link agora.');setNotice('Se houver uma conta habilitada, você receberá um link para trocar a senha.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(ready&&(!cloud||(signed&&!recovery)))return <>{cloud&&<div className="session-bar"><span>Seu espaço privado</span><button onClick={async()=>{await (await authClient())?.auth.signOut();window.location.reload();}}>Sair</button></div>}{children}</>;
 return <div className="auth-screen"><form className="panel auth-card" onSubmit={submit}><span className="mascot-avatar chat-avatar"><img src="/nexo-mascote.png" alt="Nexo"/></span><h1>{recovery?'Nova senha':'Seu espaço no Nexo'}</h1><p>Seu salário, suas contas e suas decisões, juntos.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}{!ready?<p>Verificando o acesso…</p>:<>{!recovery&&<label>E-mail<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>Senha<input type="password" minLength={8} maxLength={128} autoComplete={signup||recovery?'new-password':'current-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Aguarde…':recovery?'Salvar senha':signup?'Criar conta':'Entrar'}</button>{!recovery&&<><button type="button" className="secondary" disabled={busy} onClick={()=>{setSignup(!signup);setError('');setNotice('');}}>{signup?'Já tenho conta':'Criar uma conta'}</button><button type="button" disabled={busy||!email} onClick={()=>void reset()}>Esqueci minha senha</button></>}<small>Seus dados ficam no Supabase. Quando ativada, a IA Groq recebe sua pergunta e até duas perguntas anteriores para interpretá-las. Saldos e cadastros não são enviados à IA.</small></>}</form></div>;
}
