'use client';
import {apiFetch} from '../lib/client';
import {useEffect,useState,useRef,FormEvent} from 'react';
import Personal from './Personal';
import type {Snapshot} from '@rla-nexo/engine';
import {parseBrlCents,salaryOccurrence,salaryParts} from '@rla-nexo/engine';
type Projection={balanceCents:number;freeCents:number;reservedCents:number;bufferCents:number;commitmentsCents:number;minCashCents:number;endDate:string;timeline:{date:string;balanceCents:number;freeCents:number}[]};
type Dashboard={revision:number;storage:string;projection:Projection;consent:string;conversationMode:string;snapshot:Snapshot;alerts:{id:string;level:string;message:string}[]};
type Message={role:string;text:string;alternatives?:string[]};
type Simulation={status:string;totalCents:number;baseline:Projection;result:Projection;assumptions:string[]};
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
const date=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
async function api(path:string,body?:unknown){
 const response=await apiFetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await response.json();if(!response.ok)throw new Error(data.message||'Não foi possível concluir.');return data;
}
export default function Home(){
 const messagesEnd=useRef<HTMLDivElement>(null);
 const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('Visão geral');
 const [message,setMessage]=useState(''),[messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Olá! Sou o Nexo. Vamos olhar seu próximo passo? Pergunte quanto está livre ou diga quanto quer gastar.'}]);
 const [busy,setBusy]=useState(false),[syncing,setSyncing]=useState(false),[scenarioBusy,setScenarioBusy]=useState(false);
 const [amount,setAmount]=useState('500'),[start,setStart]=useState(''),[months,setMonths]=useState('1'),[kind,setKind]=useState('expense'),[scenario,setScenario]=useState<Simulation|null>(null);
 useEffect(()=>{const el=messagesEnd.current;if(el)el.scrollTop=el.scrollHeight;},[messages,busy]);
 async function refresh(){try{const d=await api('dashboard');setData(d);setStart(s=>s||d.snapshot.asOf);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void refresh();api('conversation/history').then(h=>{if(h.length)setMessages(h)}).catch(()=>setError('Não foi possível carregar o histórico. Recarregue a página.'));const timer=setInterval(()=>void refresh(),60000);return()=>clearInterval(timer)},[]);
 async function send(text=message){
   if(!text.trim()||busy)return;setBusy(true);setMessage('');setMessages(v=>[...v,{role:'user',text}]);
   try{const r=await api('conversation',{message:text});setMessages(v=>[...v,{role:'assistant',text:r.reply+(r.warning?' '+r.warning:''),alternatives:r.assessment?.alternatives}]);}
   catch(e){setMessages(v=>[...v,{role:'assistant',text:(e as Error).message}]);}finally{setBusy(false);}
 }
 async function connection(active?:boolean){
   setSyncing(true);setError('');
   try{if(active!==undefined)await api('open-finance/consent',{active});else await api('open-finance/sync',{});await refresh();}
   catch(e){setError((e as Error).message);}finally{setSyncing(false);}
 }
 async function runScenario(e:FormEvent){
   e.preventDefault();setScenarioBusy(true);setError('');setScenario(null);
   const value=parseBrlCents(amount);
   if(value===null||value<=0){setError('Informe um valor positivo usando vírgula nos centavos, como 500,50 ou 1.250,00.');setScenarioBusy(false);return;}
   try{setScenario(await api('scenarios',{amountCents:value,date:start,months:Number(months),kind}));}
   catch(e){setError((e as Error).message);}finally{setScenarioBusy(false);}
 }
 const p=data?.projection;
 return <div className="shell">
  <aside className="sidebar"><a href="/" className="brand"><span className="mascot-avatar brand-avatar"><img src="/nexo-mascote.png" alt="Mascote Nexo"/></span><span>RLA <b>nexo</b></span></a><div className="workspace-label">SEU ESPAÇO FINANCEIRO</div>
  <nav>{['Visão geral','Meus dados','E se?','Contas e metas','Conexões'].map((item,i)=><button key={item} onClick={()=>setTab(item)} className={tab===item?'nav active':'nav'}><span>{['◫','✎','↗','◎','⇄'][i]}</span>{item}</button>)}</nav>
  <div className="sidebar-bottom"><span className="online-dot"/> Memória ativa<p>Seus dados ficam salvos no banco de dados conectado.</p><div className="profile"><span>U</span><div>Minha conta<small>Perfil pessoal</small></div></div></div></aside>
  <main><header><div className="breadcrumb">Meu espaço <span>/</span> {tab}</div><span className="demo-label">USO PESSOAL</span></header>
  <div className="page-heading"><div><p className="eyebrow">RLA NEXO · FINANÇAS PESSOAIS</p><h1>{tab==='Visão geral'?'Mais clareza. Melhores decisões.':tab==='E se?'?'Explore seu próximo passo.':tab==='Conexões'?'Suas contas, conectadas.':'O que você quer proteger.'}</h1><p>{tab==='Visão geral'?'Entenda o que está livre antes de decidir o que vem depois.':tab==='E se?'?'Veja como uma escolha muda a sua projeção financeira.':tab==='Conexões'?'Gerencie de onde vêm seus dados financeiros.':'Compromissos e reservas que fazem parte do seu plano.'}</p></div><button className="secondary" disabled={syncing} onClick={()=>void refresh()}>↻ Recarregar</button></div>
  {error&&<div className="error" role="alert">{error}<button onClick={()=>void refresh()}>Tentar novamente</button></div>}
  {!data&&!error&&<p role="status">Preparando seu espaço financeiro…</p>}
  {data&&p&&<>
  {data.snapshot.accounts.length===0&&tab!=='Meus dados'&&<div className="onboarding-banner"><div><h2>Vamos começar pelos seus números?</h2><p>Cadastre seu saldo, salário e compromissos. Tudo fica salvo ao sair.</p></div><button className="primary" onClick={()=>setTab('Meus dados')}>Cadastrar meus dados</button></div>}
  {tab==='Meus dados'&&<Personal initial={data} onSaved={()=>void refresh()}/>}
  {tab==='Visão geral'&&<><div className="overview-grid"><section className="free-card"><div className="card-top"><span>Dinheiro livre</span><span className="light-pill">Próximos 30 dias</span></div><div className="big-number">{money(p.freeCents)}</div><p>Após proteger suas contas, metas e margem.</p><div className="free-footer"><span>◎ Caixa mínimo projetado</span><strong>{money(p.minCashCents)}</strong></div></section>
  <section className="metric"><span className="metric-icon">↙</span><p>Saldo em contas</p><h2>{money(p.balanceCents)}</h2><span>Em {data.snapshot.accounts.length} contas cadastradas</span></section>
  <section className="metric"><span className="metric-icon">◷</span><p>Compromissos</p><h2>{money(p.commitmentsCents)}</h2><span>Até {date(p.endDate)}</span></section></div>
  {data.snapshot.salary?<section className="salary-summary panel"><div><span className="eyebrow">MEU SALÁRIO</span><h2>{money(data.snapshot.salary.netCents)}<small> líquidos / mês</small></h2><p>{salaryParts(data.snapshot).map((part,i)=>{const o=salaryOccurrence(data.snapshot,part,data.snapshot.asOf.slice(0,7));return 'Parte '+(i+1)+': '+(o.status==='RECEIVED'?'recebida':o.scheduledDate<data.snapshot.asOf?'aguardando confirmação':'prevista para '+date(o.scheduledDate));}).join(' · ')}</p></div><div><span className="storage-badge">{data.snapshot.salary.active??data.snapshot.salary.confirmed?'Previsão incluída':'Pausada'}</span><button className="secondary" onClick={()=>setTab('Meus dados')}>Editar salário</button></div></section>:<section className="salary-summary panel"><div><h2>Meu salário</h2><p>Cadastre o valor líquido e os dias mensais de recebimento.</p></div><button className="secondary" onClick={()=>setTab('Meus dados')}>Cadastrar salário</button></section>}
  <div className="main-grid"><section className="conversation panel"><div className="section-heading"><div className="mascot-avatar chat-avatar"><img src="/nexo-mascote.png" alt="Mascote Nexo"/></div><div><h2>Converse com o Nexo</h2><p>Um passo de cada vez, com os números à vista.</p></div><span className="status-dot"/></div>
  <div className="messages" ref={messagesEnd} role="log" aria-live="polite">{messages.map((m,i)=><div className={'message '+m.role} key={i}><small>{m.role!=='user'&&<span className="mascot-avatar message-avatar"><img src="/nexo-mascote.png" alt=""/></span>}{m.role==='user'?'VOCÊ':'NEXO'}</small><p>{m.text}</p>{m.alternatives?.map((a,j)=><p className="alternative" key={j}>↳ {a}</p>)}</div>)}{busy&&<p role="status">{data.conversationMode==='ollama'?'O Nexo está pensando… consultas de saldo e gastos simples têm resposta rápida.':'Analisando seu pedido…'}</p>}</div>
  <div className="suggestions">{['Quero gastar 500','Quero gastar 3.000','Dinheiro livre'].map(t=><button disabled={busy} key={t} onClick={()=>send(t)}>{t} ↗</button>)}</div>
  <form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><input aria-label="Mensagem para o Nexo" placeholder="Quero gastar 500" value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000}/><button disabled={busy||!message.trim()} aria-label="Enviar mensagem">↑</button></form><div className="conversation-foot">{data.conversationMode==='ollama'?'IA neste computador · sem cobrança por mensagem':data.conversationMode==='local'?'Conversa guiada':data.conversationMode==='groq'?'IA online · cota gratuita':'Conversa com OpenAI'}<span>Simular não movimenta dinheiro</span></div></section>
  <div className="right-column"><section className="panel signals"><div className="section-title"><h2>No seu radar</h2><span className="count">{data.alerts.length}</span></div>{data.alerts.map(a=><div key={a.id} className={'signal '+a.level}><span>{a.level==='info'?'↗':'!'}</span><p>{a.message}</p></div>)}</section><section className="scenario-teaser"><span className="eyebrow">ANTES DE DECIDIR</span><h2>E se eu fizer diferente?</h2><p>Compare um gasto hoje com uma escolha para os próximos meses.</p><button onClick={()=>setTab('E se?')}>Explorar cenários <span>↗</span></button></section></div></div>
  <section className="panel formula"><h2>Como chegamos ao dinheiro livre</h2><div><span>Menor caixa<strong>{money(p.minCashCents)}</strong></span><b>−</b><span>Metas reservadas<strong>{money(p.reservedCents)}</strong></span><b>−</b><span>Margem de segurança<strong>{money(p.bufferCents)}</strong></span><b>=</b><span className="formula-total">Dinheiro livre<strong>{money(p.freeCents)}</strong></span></div><p>Entradas confirmadas e contas da mesma data são compensadas. Recebimentos futuros não ficam disponíveis hoje; confira o horário do crédito antes de pagar.</p></section></>}
  {tab==='E se?'&&<div className="simulation-grid"><form className="panel scenario-form" onSubmit={runScenario}><h2>Uma nova possibilidade</h2><label>Quero simular<select value={kind} onChange={e=>{setKind(e.target.value);setScenario(null)}}><option value="expense">Um gasto</option><option value="income">Uma entrada adicional</option></select></label><label>Valor por ocorrência (R$)<input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setScenario(null)}} required/></label><label>Data da primeira ocorrência<input type="date" min={data.snapshot.asOf} value={start} onChange={e=>{setStart(e.target.value);setScenario(null)}} required/></label><label>Ocorrências mensais<select value={months} onChange={e=>{setMonths(e.target.value);setScenario(null)}}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1===1?'Uma vez':(i+1)+' meses'}</option>)}</select></label><button className="primary" disabled={scenarioBusy}>{scenarioBusy?'Calculando…':'Simular impacto ↗'}</button><p>Os dados originais permanecem iguais. Esta é uma hipótese.</p></form>
  <section className="panel scenario-result" aria-live="polite">{!scenario?<div className="empty"><span>↗</span><h2>Um olhar para o futuro</h2><p>Escolha o valor e a data para comparar sua situação atual com o novo cenário.</p></div>:<><span className={'result-badge '+scenario.status}>{scenario.status==='safe'?'Dentro do plano':scenario.status==='bills_at_risk'?'Atenção às contas':'Atenção às metas'}</span><h2>Impacto da sua escolha</h2><div className="comparison"><div><p>Dinheiro livre · sem mudança</p><strong>{money(scenario.baseline.freeCents)}</strong></div><div><p>Dinheiro livre · com cenário</p><strong>{money(scenario.result.freeCents)}</strong></div></div><p>Total simulado: <b>{money(scenario.totalCents)}</b> · projeção até {date(scenario.result.endDate)}</p><h3>Caixa ao longo do tempo</h3><div className="timeline">{scenario.result.timeline.map((point,i)=><div key={i}><span>{date(point.date)}</span><div className="bar-track"><div className={point.balanceCents<0?'negative':''} style={{width:Math.max(2,Math.min(100,Math.abs(point.balanceCents)/Math.max(...scenario.result.timeline.map(p=>Math.abs(p.balanceCents)),1)*100))+'%'}}/></div><b>{money(point.balanceCents)}</b></div>)}</div><div className="assumptions"><h3>O que esta projeção considera</h3>{scenario.assumptions.map(a=><p key={a}>• {a}</p>)}</div></>}</section></div>}
  {tab==='Contas e metas'&&<div className="details-grid"><section className="panel"><h2>Próximos compromissos</h2>{data.snapshot.commitments.filter(c=>c.status==='pending').map(c=><div className="data-row" key={c.id}><span>{c.name}<small>{date(c.dueDate)}</small></span><strong>{money(c.amountCents)}</strong></div>)}</section><section className="panel"><h2>Reservas de metas</h2>{data.snapshot.goals.map(g=><div className="data-row" key={g.id}><span>◎ {g.name}<small>Reservado dentro do saldo</small></span><strong>{money(g.reservedCents)}</strong></div>)}<div className="data-row"><span>Margem de segurança</span><strong>{money(p.bufferCents)}</strong></div></section><section className="panel"><h2>Transações recentes</h2>{data.snapshot.transactions.map(t=><div className="data-row" key={t.id}><span>{t.description}<small>{date(t.date)}</small></span><strong className={t.amountCents>0?'positive':''}>{money(t.amountCents)}</strong></div>)}<p className="muted">Estas transações já estão refletidas no saldo.</p></section></div>}
  {tab==='Conexões'&&<div className="details-grid"><section className="panel"><h2>Memória do RLA Nexo</h2><span className="storage-badge">● PostgreSQL conectado</span><p>Saldos, salário, contas, metas, lançamentos e histórico da conversa ficam salvos no banco de dados conectado.</p><p>Última alteração: {new Date(data.snapshot.syncedAt).toLocaleString('pt-BR')}</p><button className="secondary" onClick={()=>setTab('Meus dados')}>Gerenciar dados e backup</button></section><section className="panel"><h2>Conexão bancária automática</h2><span className="demo-label">NÃO CONECTADA</span><p>Você já pode usar suas informações reais por cadastro manual. A importação automática via Open Finance depende de um provedor e do consentimento no banco.</p><h3>Sua conversa</h3><p>{data.conversationMode==='ollama'?'A IA roda neste computador. Sua conversa e seus dados ficam aqui; os cálculos são feitos pelo motor financeiro.':data.conversationMode==='groq'?'A Groq interpreta suas perguntas. Os valores e as respostas financeiras vêm do motor do Nexo. Ao atingir a cota, use consultas diretas e o simulador.':data.conversationMode==='local'?'Conversa guiada disponível sem chave: consulte dinheiro livre ou diga “Quero gastar 500”. Seu histórico fica salvo.':'A OpenAI interpreta o pedido e o motor financeiro decide os valores. Seu histórico fica salvo.'}</p></section></div>}
  <footer><span>RLA <b>nexo</b></span><span>Projeções baseadas nos dados disponíveis · BRL</span></footer>
  </>}
  </main></div>
}
